{% set name = "pysprint" %}
{% set version = "0.12.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a0c046caa49e219dd0e54a50701149687cc6f52134f201ec83180af5eb0b8cf0

build:
  number: 0

  script_env:
   - CONDA_BLD_PATH
  entry_points:
    - pysprint = pysprint.templates.build:main

requirements:
  host:
    - jinja2
    - matplotlib
    - numpy >=1.16.6
    - pandas
    - pip
    - python
    - scipy
  run:
    - jinja2
    - matplotlib
    - numpy >=1.16.6
    - pandas
    - python
    - scipy

about:
  home: "https://github.com/Ptrskay3/PySprint"
  license: MIT
  summary: "Spectrally refined interferometry for Python"
